version: '3.3'

services:
  mongo:
    image: 192.168.1.102:5000/console/mongo:4.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8030:8030
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456