spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/swhr0903/console-config.git
          search-paths: /{application}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,
      com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure,
      org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8014